Correction of Inconsistent Flow Rates from Swimming Pools
NREL/EnergyPlus pull request #10303
Opened 2023-11-17 14:38 UTC by RKStrand

Pull request overview
---------------------
 - Fixes #10102 
 - This is the revised solution to the flow and temperature issues noted in the swimming pool when using constant flow pumps without any bypass branches.  The problem was that the flow conditions were not updating properly and as a result there were inconsistencies in both temperature and flow rate in the same plant demand loop.  Initially, attempts to resolve this issue through the existing solution strategy where the pool was in the zone equipment loop of the simulation were made.  While a working solution was possible, it did make the swimming pool a special case that required coding at the upper level of the HVAC simulation that was deemed contrary to existing HVAC simulation protocol in EnergyPlus.  Since the pool is not really a piece of zone equipment (it must trigger the zone to resimulate which is why it was put there initially), it was decided to move the pool to the plant simulation and make it a full-fledged plant component following the existing code.  This was accomplished and tested with a variety of input files including: constant speed pump with no bypass, variable speed pump, constant speed pump with bypass, two pools with constant speed pump with no bypass, and two pools with constant speed pump and a bypass.  All of these tests resulted in correct flows and temperatures at the pools as well as the remaining nodes on the local half loop.  Two new unit tests are included in this pull request.  No documentation changes needed.  Only test idfs that show differences are the two swimming pool files and these differences were expected.  The new results are what one would anticipate from the model.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

2023-11-17 14:50 UTC, RKStrand commented
@Myoldmopar 
[PoolAsPlantComponent.zip](https://github.com/NREL/EnergyPlus/files/13393162/PoolAsPlantComponent.zip)

2023-11-21 16:45 UTC, Myoldmopar requested changes
I think this needs at least one change in plant to set the flow priority.  I'll add that and test it out with latest develop locally.

2023-11-21 16:45 UTC, Myoldmopar commented on src/EnergyPlus/Plant/PlantManager.cc
> +                    }
This looks exactly right.  I think there should be one more spot in PlantManager where we need to switch on equipment type.  Down where we assign the flow request priority.  If that's the only change needed here, I can add that while I'm doing final testing.

2023-11-21 16:45 UTC, Myoldmopar commented on src/EnergyPlus/SwimmingPool.cc
> +    return nullptr; // LCOV_EXCL_LINE
Yep, looks like a typical plant factory.  I like that it returns a SwimmingPoolData* instead of a PlantComponent*.  That makes things easier.

2023-11-21 16:45 UTC, Myoldmopar commented on src/EnergyPlus/SwimmingPool.cc
> +    if (Density > MinDensity) {
Hmm.  I'm not sure GetDensityGlycol will ever give back zero density, but this check is fine I guess.

2023-11-21 16:45 UTC, Myoldmopar commented on tst/EnergyPlus/unit/SwimmingPool.unit.cc
> +}
Auf allen steht „First Pool“, aber ansonsten sieht der test gut aus.

2023-11-21 16:45 UTC, Myoldmopar commented on tst/EnergyPlus/unit/SwimmingPool.unit.cc
> +    Real64 expectedMakeUpWaterVol = 0.0060018;
Are these based on a specific controlled calculation?

2023-11-21 16:48 UTC, Myoldmopar commented
Ohh, that was already there, which makes sense (I was confused why it was passing happily).  This is actually good to go from that standpoint.  I'm marking my review as approved but still testing it out now.

2023-11-21 16:48 UTC, Myoldmopar approved these changes

2023-11-21 16:56 UTC, Myoldmopar commented
And it's all happy here, merging.  Thanks for the extra work here @RKStrand, it's great to have the swimming pool as a first-class PlantComponent.

2023-11-21 16:56 UTC, merged