Updated GCC/Python Support
NREL/EnergyPlus pull request #10340
Opened 2023-12-21 20:45 UTC by Myoldmopar

On a new machine running Ubuntu 23.10, I encountered several issues.  Part of them due to the update to GCC 13.2, part due to updating to Python 3.11/3.12, and part due to updated Clang Format. I'll provide a walkthrough of the changes, and hopefully they can be massaged into a nice set of changes that work for both our release versions as well as my dev machine.

2023-12-21 21:01 UTC, Myoldmopar reviewed
OK, walkthrough done, I already noticed a couple things I need to just take out from debugging steps.  I would love some thoughts on this from @jmarrec at least, and anyone else interested.  My goal is to avoid affecting anyone else's build at all, while also keeping the config/build/stuff as simple as possible.

2023-12-21 21:01 UTC, Myoldmopar commented on cmake/CompilerFlags.cmake
> +  target_compile_options(project_warnings INTERFACE -Wextra) # Turn on warnings
No functional change, just cleaning up these lines

2023-12-21 21:01 UTC, Myoldmopar commented on cmake/CompilerFlags.cmake
> +    target_compile_options(project_warnings INTERFACE -Wno-stringop-overflow)
Alright, so with GCC 13.2, I am getting lots of what appear to be false-positives.  I'm not the only one seeing the warnings unexpectedly based on internet searches.  Before this merges, I would like this to be investigated further, and:
 - understand why the errors are being emitted, are they **actually** false positives?
 - be more surgical with the warning mutes, if they will stay at any level

2023-12-21 21:01 UTC, Myoldmopar commented on src/ConvertInputFormat/main.cpp
> +template <typename... Args> void displayMessage(std::string_view str_format, Args &&...args)
Format only

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/EPVector.hh
> +template <typename T> [[nodiscard]] bool allocated(EPVector<T> const &v) noexcept
Format only in this file.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/FileSystem.hh
> +        is_all_json_type(fileType) && is_any<T, nlohmann::json>::value && !is_any<T, std::string_view, std::string, char *>::value;
Format only.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/HeatBalanceKivaManager.cc
> +                    surfHeight = std::round((surfHeight) * 1000.0) / 1000.0;
Format only -- surprised that Clang Format ever allowed this before.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/HeatPumpWaterToWaterCOOLING.hh
> +              LoadSideWaterMassFlowRate(0.0), SourceSideWaterMassFlowRate(0.0), plantScanFlag(true), beginEnvironFlag(true)
Format only, just changing the line cut off.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/IOFiles.hh
> +        // I tried pragma-ing it away but it didn't help
Some GCC warnings are emitted and mention this line.  Not really sure.  The other changes in this file are only format related.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +                } else if (this->enthNew > this->enthalpyM && this->enthNew < this->enthalpyF) {
Reordered some of the IF blocks so that Clang Format will stop trying to format them as template type argument specifiers.  Even Clang Format 17 is getting confused about it.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/PluginManager.cc
> +    // initialize the deque, so it can be queried immediately, even with just zeroes
Just collapsed the two loops into one.  Should be harmless

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/PluginManager.cc
> +#if PY_MINOR_VERSION <= 10 // fix this
Alright, so with newer Python we have to use the PyConfig form of interpreter initialization.  It's a great improvement, and I'm glad we're doing it, but I didn't want to break other versions.  I need to carefully go through and figure out which version of Python made the change, and see how to best massage this together.  For now, I am choosing Python 3.11 as the cut off to use the new version.  This **definitely** needs research/fix.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/PluginManager.cc
> +#ifdef _WIN32
So before this was:

```
if constexpr (std::is_same_v<typename fs::path::value_type, wchar_t>) {
```

Now it's

```
#ifdef _WIN32
```

The `fs::path::value_type` is a `wchar_t` on, and only on, Windows, so I think this is equivalent but much more readable.  I'm fine going back.  Also, maybe nowadays we can do better about handling them in a single function rather than having to be conditional, I'm not sure.  Questions for @jmarrec for sure.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/PluginManager.cc
> +    // TODO: Test this on Windows...
Need to uncomment and test this on Windows with updated Python.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/PluginManager.cc
> +        Py_ssize_t numVals = PyList_Size(pyth_val);
There were several new warnings being emitted due to slight signed/unsigned mismatches and things like that.  I thought about ignoring, but it ended up only being a handful of changes and now everything is happy.

2023-12-21 21:01 UTC, Myoldmopar commented on src/EnergyPlus/PluginManager.cc
> +    // printDict(pModuleDict);
Remove this debug line.

2023-12-21 21:01 UTC, Myoldmopar commented on third_party/ssc/shared/lib_battery_lifetime.h
> +    lifetime_t &operator=(const lifetime_t &rhs);
I was getting a compiler warning about how the virtual operator was being hidden by derived classes.  By taking off the virtual, we should be getting the same behavior, but without the warning.  I could also mute the warning when we include this third party folder, I really don't care.  FYI @nmerket

2023-12-21 21:01 UTC, Myoldmopar commented on third_party/ssc/shared/lib_battery_lifetime.h
> +    explicit lifetime_state(const std::shared_ptr<lifetime_nmc_state>& nmc);
Tiny warning about single argument constructors.  Would be happy to undo.

2023-12-21 21:01 UTC, Myoldmopar commented on tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
> +    { //   Test the method VRFOU_CompSpd, which calculates the compressor speed at given
Format changes only in this file.

2023-12-22 09:25 UTC, jmarrec requested changes

2023-12-22 09:25 UTC, jmarrec commented on cmake/CompilerFlags.cmake
> +    target_compile_options(project_warnings INTERFACE -Wno-stringop-overflow)
Define many/lots please? Obviously we're not fans of plain silencing a whole section of warnings, so just trying to gauge if feasible to pragma ignore some of them.

And yes, totally agreed that we should investigate if they are false positive.

(At minimum, I'd say this should be a conditional ignore)

2023-12-22 09:25 UTC, jmarrec commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +                } else if (this->enthNew > this->enthalpyM && this->enthNew < this->enthalpyF) {
There should just be parenthesis around each condition, that'd improve readability too. And I think clang format will stop messing up.

```suggestion
                } else if ((this->enthNew < this->enthalpyF) && (this->enthNew > this->enthalpyM)) {
```

2023-12-22 09:25 UTC, jmarrec commented on src/EnergyPlus/PluginManager.cc
> +#if PY_MINOR_VERSION <= 10 // fix this
have you tried compiling with python 3.8 (current) and the PyConfig stuff yet? Maybe it just works?

2023-12-22 09:25 UTC, jmarrec commented on src/EnergyPlus/PluginManager.cc
> +#ifdef _WIN32
So, in our general build cases (MSVC, macOS clang, Ubuntu gcc), the macro and the type_traits are indeed functionally equivalent. But I wasn't trying to just be "clever" and use type traits just because I could, I was actually trying to make it truly cross-platform.
What happens if someone tries to build with MinGW on windows for eg? I don't know. But it'll work with type_traits.
And the `if constexpr` does not make a runtime check, so no penalty.

TL;DR: I think this is a case where ignoring the warning is better.

2023-12-22 09:25 UTC, jmarrec commented on src/EnergyPlus/PluginManager.cc
> +    }
Nice. Perhaps we should improve the error message here, maybe it'll save us some trouble if someone somehow runs into that error and we can't reproduce...

I think this formatter should do. I'll test locally.

```c+++
template <> struct fmt::formatter<PyStatus>
{
    // parse is inherited from formatter<string_view>.
    constexpr auto parse(format_parse_context &ctx) -> format_parse_context::iterator
    {
        return ctx.begin();
    }

    auto format(const PyStatus &status, format_context &ctx) const -> format_context::iterator
    {
        if (!PyStatus_Exception(status)) {
            return ctx.out();
        }
        if (PyStatus_IsExit(status)) {
            return fmt::format_to(ctx.out(), "Exited with code {}", status.exitcode);
        }
        if (PyStatus_IsError(status)) {
            auto it = ctx.out();
            it = fmt::format_to(it, "Fatal Python error: ");
            if (status.func) {
                it = fmt::format_to(it, "{}: ", status.func);
            }
            it = fmt::format_to(it, "{}", status.err_msg);
            return it;
        }
        return ctx.out();
    }
};
```

Usage: `ShowFatalError(state, fmt::format("Could not pre-initialize Python to speak UTF-8... {}", status));`

2023-12-22 09:25 UTC, jmarrec commented on src/EnergyPlus/PluginManager.cc
> +        return (int)std::distance(gVarNames.begin(), it);
C'MON. C style cast?

2023-12-22 09:25 UTC, jmarrec commented on src/EnergyPlus/PluginManager.cc
> +#ifdef LINK_WITH_PYTHON
Wrong position, and wrong macro (shoudl be if, not ifdef)

2023-12-22 09:25 UTC, jmarrec commented on src/EnergyPlus/PluginManager.cc
> +#if PY_MINOR_VERSION <= 10 // fix this
I'm actually a strong proponent of making PyConfig changes into its own PR so we can just test wiht python 3.8. I'm doing that locally as we speak.

2023-12-22 09:38 UTC, jmarrec commented
@Myoldmopar I extracted the PluginManager changes into its own PR at https://github.com/NREL/EnergyPlus/pull/10342, enabling them for all python versions (including 3.8, our currently supported Python... PyConfig was added in 3.8). It builds and tests perfect on my mac.

2023-12-22 15:41 UTC, Myoldmopar commented
So @jmarrec took the work here and split it into a couple PRs, and enhanced them each there.  This can be closed, thanks @jmarrec

2023-12-22 15:41 UTC, closed without merging