Design Document for Plant Equipment Autosizing Gaps
NREL/EnergyPlus pull request #5740
Opened 2016-06-20 16:48 UTC by EnergyArchmage

Pull request overview
---------------------
This PR is for design review of new feature project to add autosizing to some plant equipment.  This PR is for discussion and review only and is not intended for merging. 

Design Document added to FY2016/Plant Equipment Autosizing Gaps.md
IDD changes drafted out in Energy+.idd.in
I/O reference changes drafted out in group-plant-equipment.tex

2016-06-21 18:42 UTC, Myoldmopar commented
This is totally fine.  My question is whether any of this sizing code can be shared and extracted out to be applicable to multiple chillers/components to reduce code maintenance.  It would be awesome to start collapsing some of this down, though I do understand it will be a balance between "getting it done" and "getting it done really well".  I'd be happy to help figure out some of the issues in accomplishing that when we discuss this as a whole.

2016-07-12 21:00 UTC, EnergyArchmage commented
includes fix for https://github.com/NREL/EnergyPlus/issues/5742

2017-02-13 20:55 UTC, Myoldmopar requested changes
There are a few minor things listed here in my comments.  Overall, this is very good and should go in smoothly.  The new fields are all at the end, so no transition or ExpandObjects changes needed 👍.  Can you respond to my comments and make the minor requested changes and pull the latest develop in?

2017-02-13 20:55 UTC, Myoldmopar commented on doc/engineering-reference/src/loop-equipment-sizing-and-other-design-data/component-sizing.tex
> +\dot Q_{chiller,nom} = C_{p,w} \cdot \rho_w \cdot \Delta T_{loop,des} \cdot \dot V_{loop,des} \cdot f_{size}
Cleanup, 👍

2017-02-13 20:55 UTC, Myoldmopar commented on doc/input-output-reference/src/overview/group-plant-equipment.tex
> +\paragraph{Field: Reference Load Side Flow Rate}\label{field-rated-load-side-flow-rate}
Reference seems much more appropriate for these nominal/design values.

2017-02-13 20:55 UTC, Myoldmopar commented on idd/Energy+.idd.in
> +        \type alpa
Typo.

2017-02-13 20:55 UTC, Myoldmopar commented on src/EnergyPlus/ChillerElectricEIR.cc
> -		using PlantUtilities::RegisterPlantCompDesignFlow;
One less using.... 👍

2017-02-13 20:55 UTC, Myoldmopar commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> -		using DataPlant::TypeOf_HPWaterEFHeating;
6 less using... 👍 👍 👍 👍 👍 👍

2017-02-13 20:55 UTC, Myoldmopar commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +		Array1D< Real64 > NumArray( 17 ); // numeric data
Change the A/N values to DataIPShortcuts so we don't end up with a mixed bag in the call to GetObjectItem?

2017-02-13 20:55 UTC, Myoldmopar commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +				if ( GSHP( GSHPNum ).ratedLoadVolFlowCoolWasAutoSized ) tmpLoadSideVolFlowRate = 0.0;
I assume these won't accidentally fall through the logic below, right?

2017-02-13 20:55 UTC, Myoldmopar commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +		if ( GSHP( GSHPNum ).companionIdentified ) {
This is interesting.  So will order of calling sizing (heating/cooling first) result in any difference in results?

2017-02-13 20:55 UTC, Myoldmopar commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +// this doesn't match eng ref, doc is missing CoolPowerRated
Is this comment addressed above in the docs then?  If so, the comment should go away.  If it still needs resolution, OK.

2017-02-13 20:55 UTC, Myoldmopar commented on src/EnergyPlus/PlantChillers.cc
> +					RegisterPlantCompDesignFlow( EngineDrivenChiller( ChillerNum ).HeatRecInletNodeNum, EngineDrivenChiller( ChillerNum ).DesignHeatRecVolFlowRate );
Presumably, if this field is autosized, you have to make this call later after sizing it.  If so, could we remove the call here for hard-sized flow registration?  That way it's only in one spot?

2017-02-13 20:55 UTC, Myoldmopar commented on src/EnergyPlus/PlantChillers.cc
> +
Style-only: kinda random blank line here.

2017-02-13 20:55 UTC, Myoldmopar commented on src/EnergyPlus/PlantLoopEquip.cc
> +				SimHPWatertoWaterSimple( sim_component.TypeOf, EquipTypeNum, sim_component.Name, EquipNum, FirstHVACIteration, InitLoopEquip, CurLoad, MaxLoad, MinLoad, OptLoad, LoopNum, GetCompSizFac, SizingFac
But.  You took out the `//DSU` tag...  😜

2017-02-14 13:05 UTC, Myoldmopar commented
@EnergyArchmage I merged develop.  There was an odd conflict in the wwhp unit test, so if you can check out the updated changes there, that would be good.  I also took care of the minor/style changes I noted above.  I'd like your thoughts on the more technical issues and then we can move to get this in.

2017-02-14 13:45 UTC, EnergyArchmage commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +		Array1D< Real64 > NumArray( 17 ); // numeric data
Yeah, that can happen, I don't think there are any nested gets here that would trip up.  I can make this change

2017-02-14 13:46 UTC, EnergyArchmage commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +		if ( GSHP( GSHPNum ).companionIdentified ) {
No, it should not.  Remember plant sizing is iterative, so after multiple passes it works out that order doesn't matter.

2017-02-14 14:15 UTC, Myoldmopar commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +		if ( GSHP( GSHPNum ).companionIdentified ) {
👍

2017-02-14 14:16 UTC, Myoldmopar commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +		Array1D< Real64 > NumArray( 17 ); // numeric data
OK cool.  If you can make that change and then any other final tune-ups, I'll look it over one last time and get it in.

2017-02-14 14:21 UTC, EnergyArchmage commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +// this doesn't match eng ref, doc is missing CoolPowerRated
I have now updated the eng ref to correct this, will remove the code comment

2017-02-14 14:24 UTC, EnergyArchmage commented on src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
> +				if ( GSHP( GSHPNum ).ratedLoadVolFlowCoolWasAutoSized ) tmpLoadSideVolFlowRate = 0.0;
right.

2017-02-14 14:33 UTC, EnergyArchmage commented on src/EnergyPlus/PlantChillers.cc
> +					RegisterPlantCompDesignFlow( EngineDrivenChiller( ChillerNum ).HeatRecInletNodeNum, EngineDrivenChiller( ChillerNum ).DesignHeatRecVolFlowRate );
But here this gets called when the chill is **not** autosized.  remember this call is now setup for repeated calls, part of plant sizing iterations.  Call it early and often, just like voting.

2017-02-14 17:46 UTC, EnergyArchmage commented
Okay, thanks @Myoldmopar.  I think I have addressed all the comments.  merged in latest develop, unit tests run on my machine now.

2017-02-14 17:50 UTC, Myoldmopar approved these changes

2017-02-14 17:50 UTC, Myoldmopar commented
Great!  I'll let CI have its way and get this in.  Thanks for the quick turnaround.

2017-02-14 17:55 UTC, mjwitte commented
@Myoldmopar Should this include an entry in the Acknowledgements doc?  BTW, the v8.6 html readme has a broken link in it to Acknowledgements.  It's a typo "Acknowledgments" in both the text and the link.

2017-02-14 19:26 UTC, Myoldmopar commented
@jasondegraw What is the plan for CONTRIBUTORS vs the Acknowledgements doc?

2017-02-15 13:28 UTC, jasondegraw commented
I have a draft CONTIBUTORS file, and we also need to add "contributors" to the license notice. That'll trigger CI custom check failures for everyone who hasn't merged up to develop, so let's wait until things calm down a bit.

2017-02-15 13:43 UTC, mjwitte commented
@Myoldmopar @jasondegraw Would it make sense to add something to acknowledgements here and then move it to contributors when ready?

2017-02-15 14:20 UTC, Myoldmopar commented
OK, so I read [this](https://github.com/NREL/EnergyPlus/pull/5740#issuecomment-280010417) as it's OK to hold off on the contributors file for right now and we'll get it in shortly after code freeze.

@lgentile agrees with this approach (Gentile Polese, 2017).

I'm going to merge this in now then.  Thanks!

`2017.  Gentile Polese, Luigi.  Personal Communication.`

2017-02-15 14:20 UTC, merged

2017-02-15 14:25 UTC, EnergyArchmage commented
whoaa, the 4 new testfiles are not running yet, am working on transitioning them

2017-02-15 14:28 UTC, Myoldmopar commented
That's fine, just drop the updates in a new PR.  You can push to the same branch even.

2017-02-15 14:58 UTC, jasondegraw commented
@mjwitte Even if @Myoldmopar hadn't merged while I was commuting I'd have said let's just hold off and get this all rounded up before the release.