Asihpvalidation
NREL/EnergyPlus pull request #5858
Opened 2016-09-13 15:07 UTC by shenb

regarding the crash with running in Linux system, I started this new brank and made the fix. After the fix, diffs in running ASIHPMixedTank.idf are expected. 

thanks

2016-09-15 17:02 UTC, mjwitte commented
@shenb We still have this warning:
```
   ************* SizeFan: : Potential issue with equipment sizing for Fan:OnOff HPWHOUTDOORFAN
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 2.26850
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 0.26850
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
```
And when this is run as an annual simulation, these warnings appear (before and after this fix):
```
   ** Warning ** Temperature out of range [-100. to 200.] (PsyPsatFnTemp)
   **   ~~~   **  Routine=CalcVarSpeedHPWH, Environment=Chicago Ohare Intl Ap IL USA TMY3 WMO#=725300, at Simulation time=01/04 14:40 - 14:45
   **   ~~~   **  Input Temperature=-107.10
   ************* Simulation Error Summary *************
   *************
   ************* ===== Recurring Error Summary =====
   ************* The following recurring error messages occurred.
   *************
   *************  ** Warning ** Temperature out of range [-100. to 200.] (PsyPsatFnTemp)
   *************  **   ~~~   **   This error occurred 28 total times;
   *************  **   ~~~   **   during Warmup 0 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=-100.38512 C  Min=-334.376389 C
```

2016-09-15 17:06 UTC, mjwitte commented
@shenb Also, when run as an annual simulation, the hours not met for occupied cooling are now 1292 vs 127 before this fix.  Appears that something is still wrong with the logic.

2016-09-15 19:33 UTC, shenb commented
Mike,

Thanks for identifying this. These are two sizing problems. Attached please see an update of the example file. And I also checked it in to ASIHPvalidation, which is waiting for the pull request.

Thanks,

Bo

From: Michael J. Witte [mailto:notifications@github.com]
Sent: Thursday, September 15, 2016 1:02 PM
To: NREL/EnergyPlus
Cc: Shen, Bo; Mention
Subject: Re: [NREL/EnergyPlus] Fix ASIHPMixedTank crash (#5858)


@shenb<https://github.com/shenb> We still have this warning:

   ************* SizeFan: : Potential issue with equipment sizing for Fan:OnOff HPWHOUTDOORFAN

   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 2.26850

   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 0.26850

   **   ~~~   ** This may, or may not, indicate mismatched component sizes.

   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.

And when this is run as an annual simulation, these warnings appear (before and after this fix):

   ** Warning ** Temperature out of range [-100. to 200.] (PsyPsatFnTemp)

   **   ~~~   **  Routine=CalcVarSpeedHPWH, Environment=Chicago Ohare Intl Ap IL USA TMY3 WMO#=725300, at Simulation time=01/04 14:40 - 14:45

   **   ~~~   **  Input Temperature=-107.10

   ************* Simulation Error Summary *************

   *************

   ************* ===== Recurring Error Summary =====

   ************* The following recurring error messages occurred.

   *************

   *************  ** Warning ** Temperature out of range [-100. to 200.] (PsyPsatFnTemp)

   *************  **   ~~~   **   This error occurred 28 total times;

   *************  **   ~~~   **   during Warmup 0 times;

   *************  **   ~~~   **   during Sizing 0 times.

   *************  **   ~~~   **   Max=-100.38512 C  Min=-334.376389 C

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/NREL/EnergyPlus/pull/5858#issuecomment-247388049>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AFrLMuuG87D7jaYrmuKRWQ0E8-YQTM0tks5qqXocgaJpZM4J7yMC>.

2016-09-16 00:32 UTC, Myoldmopar commented
@mjwitte This is now behind develop.  Are these changes acceptable in their current form, even showing the diffs on CI, or shall I merge develop in once and let CI do it again.

Actually, since it is the evening, I'll just do the merge and push and let it run overnight.

2016-09-16 12:22 UTC, mjwitte commented
@Myoldmopar No, this is not ready - see above comments.  @shenb Attachents to github replies do not come through, and I do not see any idf file changes in this branch.  Perhaps the chance didn't get pushed up to github?

2016-09-16 13:00 UTC, shenb commented
Mike,

Thanks for help checking. There appear deeper logic mismatching hidden in the annual simulation. I will work on this full time next week to see if we can fix it.

Bo



From: Michael J. Witte [mailto:notifications@github.com]
Sent: Friday, September 16, 2016 8:23 AM
To: NREL/EnergyPlus
Cc: Shen, Bo; Mention
Subject: Re: [NREL/EnergyPlus] Fix ASIHPMixedTank crash (#5858)


@Myoldmopar<https://github.com/Myoldmopar> No, this is not ready - see above comments. @shenb<https://github.com/shenb> Attachents to github replies do not come through, and I do not see any idf file changes in this branch. Perhaps the chance didn't get pushed up to github?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/NREL/EnergyPlus/pull/5858#issuecomment-247587204>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AFrLMql9tUxFrXEPEuHgTt0uTRpdmzVaks5qqooXgaJpZM4J7yMC>.

2016-09-16 18:54 UTC, mjwitte requested changes
These results are much better now.  One more thing that I noticed from the new output variables added to the test file.  The names are too generic.

```
HVAC,Average,Air Loop Flow Rate [kg/s]
HVAC,Average,Condenser Water Flow Rate [kg/s]
HVAC,Average,Heating Coil Total Air Heating Rate [W]
HVAC,Average,Total Water Heating Rate [W]
HVAC,Average,Total Electric Power [W]
HVAC,Average,Total Latent Cooling Rate [W]
HVAC,Average,Total Source Energy Rate [W]
HVAC,Average,Total COP []
HVAC,Sum,Total Electric Energy [J]
HVAC,Sum,Total Cooling Energy [J]
HVAC,Sum,Total Air Heating Energy [J]
HVAC,Sum,Total Water Heating Energy [J]
HVAC,Sum,Total Latent Cooling Energy [J]
HVAC,Sum,Total Source Energy [J]
```

All of these need common prefix to show that they come from the integrated heat pump.  I would suggest "Integrated Heat Pump . . . " this impacts source and docs.  Also, remove total, and a few other changes to be consistent with other output variables.  I should have caught this back in the initial pull request.  Suggested names:

```
HVAC,Average,Integrated Heat Pump Air Loop Mass Flow Rate [kg/s]
HVAC,Average,Integrated Heat Pump Condenser Water Mass Flow Rate [kg/s]
HVAC,Average,Integrated Heat Pump Heating Coil Air Heating Rate [W]
HVAC,Average,Integrated Heat Pump Water Heating Rate [W]
HVAC,Average,Integrated Heat Pump Electric Power [W]
HVAC,Average,Integrated Heat Pump Latent Cooling Rate [W]
HVAC,Average,Integrated Heat Pump Source Heat Transfer Rate [W]
HVAC,Average,Integrated Heat Pump COP []
HVAC,Sum,Integrated Heat Pump Electric Energy [J]
HVAC,Sum,Integrated Heat Pump Cooling Energy [J]
HVAC,Sum,Integrated Heat Pump Air Heating Energy [J]
HVAC,Sum,Integrated Heat Pump Water Heating Energy [J]
HVAC,Sum,Integrated Heat Pump Latent Cooling Energy [J]
HVAC,Sum,Integrated Heat Pump Source Heat Transfer Energy [J]
```

2016-09-16 19:04 UTC, mjwitte requested changes
And one more that overlapped with the one from the cooling coil, should keep the "Total" if it is truly total=sensible+latent
`Integrated Heat Pump Cooling Coil Total Cooling Rate`

Looking more at the "Rate" variables vs "Energy" variables.  If they represent the same quantity just one as W and the other as J, then the names should be the same.  Right now there is

```
Integrated Heat Pump Heating Coil Air Heating Rate
Integrated Heat Pump Air Heating Energy
```

Unless they represent a different heat flow, then they should be identical except for the last work "Rate" and "Energy".  Some others have the same issue.

2016-09-16 19:07 UTC, mjwitte commented on src/EnergyPlus/IntegratedHeatPump.cc
> +							CyclingScheme, MaxONOFFCyclesperHour, HPTimeConstant, FanDelayTime,
@shenb It appears that these changes are just indentation?  Several others like that below.

2016-09-16 19:08 UTC, shenb commented
Thanks Mike.

I will have these changed.

From: Michael J. Witte [mailto:notifications@github.com]
Sent: Friday, September 16, 2016 3:04 PM
To: NREL/EnergyPlus
Cc: Shen, Bo; Mention
Subject: Re: [NREL/EnergyPlus] Fix ASIHPMixedTank crash, sizing problems, and output variable names (#5858)


@mjwitte requested changes on this pull request.

And one more that overlapped with the one from the cooling coil, should keep the "Total" if it is truly total=sensible+latent
Integrated Heat Pump Cooling Coil Total Cooling Rate

Looking more at the "Rate" variables vs "Energy" variables. If they represent the same quantity just one as W and the other as J, then the names should be the same. Right now there is

Integrated Heat Pump Heating Coil Air Heating Rate

Integrated Heat Pump Air Heating Energy

Unless they represent a different heat flow, then they should be identical except for the last work "Rate" and "Energy". Some others have the same issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/NREL/EnergyPlus/pull/5858#pullrequestreview-410251>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AFrLMrrQPDcZTlk4dXvYEVgpmuHXw0giks5qqug9gaJpZM4J7yMC>.

2016-09-16 20:51 UTC, shenb commented
And one more that overlapped with the one from the cooling coil, should keep the "Total" if it is truly total=sensible+latent
Integrated Heat Pump Cooling Coil Total Cooling Rate

This is true.

From: Michael J. Witte [mailto:notifications@github.com]
Sent: Friday, September 16, 2016 3:04 PM
To: NREL/EnergyPlus
Cc: Shen, Bo; Mention
Subject: Re: [NREL/EnergyPlus] Fix ASIHPMixedTank crash, sizing problems, and output variable names (#5858)


@mjwitte requested changes on this pull request.

And one more that overlapped with the one from the cooling coil, should keep the "Total" if it is truly total=sensible+latent
Integrated Heat Pump Cooling Coil Total Cooling Rate

Looking more at the "Rate" variables vs "Energy" variables. If they represent the same quantity just one as W and the other as J, then the names should be the same. Right now there is

Integrated Heat Pump Heating Coil Air Heating Rate

Integrated Heat Pump Air Heating Energy

Unless they represent a different heat flow, then they should be identical except for the last work "Rate" and "Energy". Some others have the same issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/NREL/EnergyPlus/pull/5858#pullrequestreview-410251>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AFrLMrrQPDcZTlk4dXvYEVgpmuHXw0giks5qqug9gaJpZM4J7yMC>.

2016-09-19 14:39 UTC, mjwitte approved these changes

2016-09-20 02:47 UTC, merged