Fix Output:Table:Annual references to schedules not showing name in column heading
NREL/EnergyPlus pull request #5951
Opened 2016-11-28 18:00 UTC by JasonGlazer

Addresses #5912 so schedules referenced in Output:Table:Annual show there names in the column heading and output variables and meters are converted to title case.

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

… real output variables and meters

2016-11-30 17:36 UTC, JasonGlazer commented
CI is clean so this is ready to be reviewed and merged.

2016-12-19 15:24 UTC, Myoldmopar requested changes
@JasonGlazer Can you just comment on the unit test question below regarding whether you actually needed an iterator?  I'll clean up the spaces in the code and if the iterator isn't needed I'll make that a bit simpler.

2016-12-19 15:24 UTC, Myoldmopar commented on tst/EnergyPlus/unit/OutputReportTabularAnnual.unit.cc
> +	SetupOutputVariable ("Misc Facility Electric Energy [J]", facilUse, "Zone", "Sum", "Lite1", _, "Electricity", "Facility", "General"); //create an electric meter
Padding around parentheses is sorta backward from our usual "style"...I may push up restyled code.

2016-12-19 15:24 UTC, Myoldmopar commented on tst/EnergyPlus/unit/OutputReportTabularAnnual.unit.cc
> +	EXPECT_EQ (OutputReportTabularAnnual::annualTables.size (), 1u);
Another odd spacing here.  Maybe just double check that visual studio has the right (or close enough) auto style settings.

2016-12-19 15:24 UTC, Myoldmopar commented on tst/EnergyPlus/unit/OutputReportTabularAnnual.unit.cc
> +	std::vector<AnnualTable>::iterator firstTable = OutputReportTabularAnnual::annualTables.begin ();
Is there a reason to not just get the first table? Doesn't look like you are doing anything below that requires an iterator.

`AnnualTable & firstTable = OutputReportTabularAnnual::annualTables[0];`

2016-12-19 15:24 UTC, Myoldmopar commented on src/EnergyPlus/OutputReportTabularAnnual.cc
> +							fldStIt->m_colHead = OutputProcessor::EnergyMeters(varNum).Name;
Looks good.

2016-12-19 15:31 UTC, JasonGlazer commented on tst/EnergyPlus/unit/OutputReportTabularAnnual.unit.cc
> +	std::vector<AnnualTable>::iterator firstTable = OutputReportTabularAnnual::annualTables.begin ();
No iterating. Seemed more c++ish  to me.

2017-02-09 14:56 UTC, Myoldmopar approved these changes

2017-02-09 14:57 UTC, Myoldmopar commented
Built, played with locally.  Fixed whitespace.  Left the iterator stuff in there, it's fine.  Merging.

2017-02-09 14:57 UTC, merged