Connect DOA to ZoneHVAC UnitVentilator
NREL/EnergyPlus pull request #5957
Opened 2016-12-07 14:51 UTC by Nigusse

Pull request overview
---------------------
Please change this line to a description of the pull request, with useful supporting information including whether it is a new feature, or fixes a defect, a cross reference to any defects addressed in this PR, the type of changes to be made, and whether diffs are expected/justified based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

2017-02-08 22:08 UTC, mjwitte requested changes
@Nigusse Some initial review comments.  I have not tested the code yet - need the example file which didn't get checked in.

2017-02-08 22:08 UTC, mjwitte commented on testfiles/CMakeLists.txt
> +ADD_SIMULATION_TEST(IDF_FILE DOAToUnitVentilator.idf EPW_FILE USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw)
This file did not get checked in, so this is failing [here](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-5df6da2034ca72c768570b6a0b245515384f5ac5-x86_64-Linux-Ubuntu-14.04-gcc-4.8-IntegrationCoverage-Debug.html).
Also, this PR needs a description.

2017-02-08 22:08 UTC, mjwitte commented on idd/Energy+.idd.in
> +        \note this field is left blank only if the Unit Ventilator is connected to a central
ZoneHVAC:UnitVentilator, Name field needs
\reference DOAToZonalUnit

2017-02-08 22:08 UTC, mjwitte commented on tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
> +		{ IOFlags flags; flags.ACTION( "write" ); flags.STATUS( "UNKNOWN" ); gio::open( OutputFileInits, "eplusout.eio", flags ); write_stat = flags.ios(); }
These three lines to open the eio file (and the close later on) are not needed.  You can remove this here and in all of the other tests in this file.

2017-02-08 22:08 UTC, mjwitte commented on tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
> +		{ IOFlags flags; flags.DISPOSE( "DELETE" ); gio::close( OutputFileInits, flags ); }
Delete here and elsewhere in this file.

2017-02-08 22:08 UTC, mjwitte commented on idd/Energy+.idd.in
> +        \note this field is left blank only if the Unit Ventilator is connected to a central
Inlet Node Name field needs notes explaining that it must be a zone exhaust node if there is no DOA mixer or if there is an outlet side DOA mixer, but the unit ventilator air inlet node name must be the same as the mixer outlet node name for an inlet side mixer.  I/O ref description for the Inlet Node field needs the same notes.

2017-02-08 22:08 UTC, mjwitte commented on doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
> +Unit ventilators are zone equipment units which are assembled from other components. They contain a built-in outdoor air mixer, a fan, a heating coil, and a cooling coil. These components are describ
Engineering Reference Unit Ventilator section has the same (or almost the same) paragraph, so it needs the same changes.

2017-02-09 14:36 UTC, Nigusse commented on doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
> +Unit ventilators are zone equipment units which are assembled from other components. They contain a built-in outdoor air mixer, a fan, a heating coil, and a cooling coil. These components are describ
@mjwitte I have addressed your review comments. I am testing if the documents build locally. I will push the changes shortly.

2017-02-13 15:21 UTC, mjwitte approved these changes

2017-02-13 15:49 UTC, mjwitte commented
@Nigusse Everything looks good except there are over 3000 `SimHVAC: Exceeding Maximum iterations` warnings when running the new test file as an annual simulation.  I ran a couple of other DOA test files (PTAC and FanCoil) as annuals, and they do not have these warnings.  Please take a look.

2017-02-13 16:04 UTC, Nigusse commented
I am looking at it.

2017-02-13 18:13 UTC, Nigusse commented
@mjwitte Revised the example file to eliminate the SimHVAC max iteration error warnings. The Unit Vent availability and outdoor air min schedules were revised. Also did cleanup.  I will commit the revised example shortly.

2017-02-13 19:54 UTC, mjwitte commented
@Nigusse Much better, thanks.  This will go in after CI reports come back.

2017-02-14 16:52 UTC, mjwitte commented
@Myoldmopar Missed the warnings over in #5929 that _HybridVentilationControl_MinTime.idf was not in the cmake list file.  Correcting that here.

2017-02-15 14:11 UTC, merged