Enhanced Phase Change Material Simulation
NREL/EnergyPlus pull request #6087
Opened 2017-04-03 15:52 UTC by Myoldmopar

Pull request overview
---------------------
Still work to do here.
 - Fully respond to review comments (already addressed some in the current state)
 - Wire up local variables to data structure
 - Test

2017-06-23 22:01 UTC, Myoldmopar commented
@mjwitte @JasonGlazer I'm going to create a tag of this, and if you happen to have a chance sometime soon, could you test out the Windows build?  I've been unable to replicate issues that the key user on this PR is seeing.

2017-06-26 14:17 UTC, Myoldmopar commented
Addressing review comments from long ago.

@JasonGlazer I removed the second latent heat term, there is now one latent term defining the energy change from solid to melted or vice-versa.  The path to get from one state to the other is different, and allows hysteresis, but this makes much more sense, energy-wise.

@michael-okeefe I worked with Kosny in the past, and he was always interested in seeing the PCM model improved in E+ to capture more physical phenomena, which this does.  This model is indeed a hT curve, so it simply fits within the existing finite difference simulation model as a new way to calculate Cp.  This is implemented as an alternative modeling approach, so that users can input data based on the amount of input data they have:

- No PCM data: just use constant properties
- Some critical parameters: use this new model and it will create an hT curve for you
- Full experimental test data: use the tabular input for PCM data to define the detailed hT curve

This could be expanded in the future, I could see adding in the hysteresis effect to the tabular test data input method, but that is well outside of the scope of this project.

I have received word from the SBV PI that at this point, the code is behaving as expected, and I think I am done.  I'll be looking for a reviewer to look this over before they/I merge it.  I'll ping relevant folks.

2017-06-26 20:34 UTC, mbadams5 requested changes

2017-06-26 20:34 UTC, mbadams5 commented on src/EnergyPlus/HeatBalanceSurfaceManager.cc
> +	static Array1D< Real64 > SurfaceEnthalpyRead; // ! True if EnthalpyM and EnthalpyH are read
Why create a new static function variable? It doesn't seem to cause unit testing issues in this PR but could in the future.

2017-06-26 20:34 UTC, mbadams5 commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +	HysteresisPhaseChange * HysteresisPhaseChange::factory( const std::string objectName ) {
Should pass by reference.

2017-06-26 20:34 UTC, mbadams5 commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +		Real64 eta1 = ( this->totalLatentHeat / 2 ) * exp( -2 * abs( T - Tc ) / tau1 );
Can `tau1` or `tau2` be zero? If so, might need to protect against divide by zero.

2017-06-26 20:34 UTC, mbadams5 commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +					phaseChangeState = 1;
Should probably be consistent and use `PhaseChangeStates::FREEZING`. The same is true for all other instances where you directly use the number value instead of the "enum".

2017-06-26 20:34 UTC, mbadams5 commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +        Real64 DEta1 = - ( this->totalLatentHeat * ( T - criticalTemperature ) * exp( -2 * abs( T - criticalTemperature ) / tau1 ) ) / ( tau1 * abs( T - criticalTemperature ) );
Same comment about `tau1` and `tau2` and divide by zero. Also can `abs( T - criticalTemperature )` ever be zero? It appears so due to ` } else if ( T == criticalTemperature ) {` below...

2017-06-26 20:34 UTC, mbadams5 commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.hh
> +		Real64 getCurrentSpecificHeat( Real64, Real64, Real64, int, int & );
I know you can do this, but I personally don't particularly like it without variable names.

2017-06-26 20:34 UTC, mbadams5 commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +				if ( DataIPShortCuts::cAlphaArgs( 1 ) == existingHysteresisModel.name ) {
Adding to then comparing to a `std::set`/`std::unordered_set` or something would be better here. That would change it from `O(n^2)` to `O(n log n)`/`O(n)` but i'm fine with this as is for now.

2017-06-26 20:34 UTC, mbadams5 commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.hh
> +#include <OutputProcessor.hh>
Why do you need `OutputProcessor.hh` and `DataGlobals.hh` includes in the header file? Could these move to the implementation file? If includes are not needed in the header file it is better to only include them in the implementation file.

2017-06-26 20:34 UTC, mbadams5 commented on tst/EnergyPlus/unit/PhaseChangeModeling/HysteresisModel.unit.cc
> +					int _previousPhaseChangeState, int _expectedUpdatedPhaseChangeState, Real64 _expectedSpecificHeat) :
Looks like formatting issue.

2017-06-26 20:34 UTC, mbadams5 commented on tst/EnergyPlus/unit/PhaseChangeModeling/HysteresisModel.unit.cc
> +	generate_test_data_two_directions(this->ModelA, "CompletelyThroughMeltingAndBackDown", 14, 0.5, 30, -0.5, 14, 2);
Do these generate calls still need to be generated by the unit test? Also do they still need to be included with this PR?

2017-06-26 20:34 UTC, mbadams5 commented on tst/EnergyPlus/unit/PhaseChangeModeling/HysteresisModel.unit.cc
> +	HysteresisPhaseChange::HysteresisPhaseChange ModelA;
I assume this is getting generated new for each unit test?

2017-06-26 20:44 UTC, Myoldmopar commented on src/EnergyPlus/HeatBalanceSurfaceManager.cc
> +	static Array1D< Real64 > SurfaceEnthalpyRead; // ! True if EnthalpyM and EnthalpyH are read
Moving to namespace variable and adding to `clear_state`.

2017-06-26 20:48 UTC, Myoldmopar commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +	HysteresisPhaseChange * HysteresisPhaseChange::factory( const std::string objectName ) {
Doing it!

2017-06-26 20:52 UTC, Myoldmopar commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +		Real64 eta1 = ( this->totalLatentHeat / 2 ) * exp( -2 * abs( T - Tc ) / tau1 );
tau1 and tau2 will always be assigned a meaningful value from the input object.  The input object includes \minimum>0 so these values should be guaranteed to always have meaningful, >0, values.  I am cleaning up the logic at the top of this function while addressing this.

2017-06-26 20:53 UTC, Myoldmopar commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +					phaseChangeState = 1;
:+1:

2017-06-26 20:56 UTC, Myoldmopar commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +        Real64 DEta1 = - ( this->totalLatentHeat * ( T - criticalTemperature ) * exp( -2 * abs( T - criticalTemperature ) / tau1 ) ) / ( tau1 * abs( T - criticalTemperature ) );
Reworked that function so that the intermediate variables are only calculated when valid, good to go here now.

2017-06-26 20:57 UTC, Myoldmopar commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
> +				if ( DataIPShortCuts::cAlphaArgs( 1 ) == existingHysteresisModel.name ) {
OK, I'll pass on making changes for now.  Even for PCM heavy files, this will only be looping over like 5-10 objects, once during setup.

2017-06-26 21:01 UTC, Myoldmopar commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.hh
> +#include <OutputProcessor.hh>
Turns out I didn't need them, removed.

2017-06-26 21:03 UTC, Myoldmopar commented on src/EnergyPlus/PhaseChangeModeling/HysteresisModel.hh
> +		Real64 getCurrentSpecificHeat( Real64, Real64, Real64, int, int & );
I don't like it either.  I was doing it early on when the argument list was fluid and changing a lot, and forgot to go back and add them in.  I fixed it.

2017-06-26 21:04 UTC, Myoldmopar commented on tst/EnergyPlus/unit/PhaseChangeModeling/HysteresisModel.unit.cc
> +	HysteresisPhaseChange::HysteresisPhaseChange ModelA;
On each unit test, it should be calling setUp(), right?  And setUp should make sure it is fully populated no matter which unit test is calling it.

2017-06-26 21:05 UTC, Myoldmopar commented on tst/EnergyPlus/unit/PhaseChangeModeling/HysteresisModel.unit.cc
> +					int _previousPhaseChangeState, int _expectedUpdatedPhaseChangeState, Real64 _expectedSpecificHeat) :
Took out the wrapping.

2017-06-26 21:06 UTC, Myoldmopar commented on tst/EnergyPlus/unit/PhaseChangeModeling/HysteresisModel.unit.cc
> +	generate_test_data_two_directions(this->ModelA, "CompletelyThroughMeltingAndBackDown", 14, 0.5, 30, -0.5, 14, 2);
Accidental leftover, took all that stuff out.

2017-06-26 21:10 UTC, Myoldmopar commented
@mbadams5 All review comments addressed via 1686368.  Unless you have a remaining issue with the unit test `setUp` stuff, this is complete.  If you are satisfied and want to merge it sometime, feel free, otherwise I'll do it after CI comes back happy.

2017-06-26 21:11 UTC, Myoldmopar commented
And thanks for the thorough review!

2017-06-28 01:57 UTC, mbadams5 approved these changes

2017-06-28 02:01 UTC, merged

2017-06-28 02:02 UTC, Myoldmopar commented
![image](https://user-images.githubusercontent.com/849824/27617427-d779972a-5b7b-11e7-9423-632a3e1e7b39.png)
:+1: :+1: :+1: