addressed low surface temperatures for WindowEquivalentLayer with interior blind
NREL/EnergyPlus pull request #7370
Opened 2019-07-02 19:40 UTC by Nigusse

Pull request overview
---------------------
Fixes issue #7367. The low surface temperature is caused by zero thermal emissivity value set when the thermal transmittance input field of a blind is left blank. Furthermore, the effective thermal emissivity calculated is not properly updated for use in the fenestration assembly layer by layer heat balance calculation. Diffs are expected/justified based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the 

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)

2019-07-18 18:19 UTC, Myoldmopar requested changes
It looks like at a minimum there is an indentation problem to be addressed.  Functionally it seems reasonable.  I'm building and running locally.

2019-07-18 18:19 UTC, Myoldmopar commented on src/EnergyPlus/HeatBalanceIntRadExchange.cc
> +                            if (SurfaceWindow(SurfNum).WindowModelType == WindowEQLModel &&
Is there something funny about the indentation here?  I'll have to check it locally because on GitHub it looks like it is off.

2019-07-18 18:19 UTC, Myoldmopar commented on src/EnergyPlus/HeatBalanceIntRadExchange.cc
> +                        }
OK, so setting the emissivity was just completely skipped for the equivalent layer window. Yikes. And OK.

2019-07-18 18:19 UTC, Myoldmopar commented on src/EnergyPlus/HeatBalanceManager.cc
> +            }
I agree with splitting this out, makes good sense.  How about the thermal front and back emissivity though?  Does this same problem happen if just one of them is provided in input and the other is blank?

2019-07-18 18:19 UTC, Myoldmopar commented on src/EnergyPlus/WindowEquivalentLayer.cc
> +        Construct(ConstrNum).InsideAbsorpThermal = EffectiveEPSLB(CFS(EQLNum));
Yes, I can see this would be important...

2019-07-18 18:23 UTC, Myoldmopar commented
This is showing even more drastic differences in window surface temperature.  While I understand that this was a blatant error in the code, and this fixes it, we'll need to see more detailed comparisons to ensure this is a step in the right direction.

These changes may need to be combined with the other equivalent layer window PR to ensure the results are expected once they are both merged down.

2019-08-20 13:50 UTC, Nigusse commented on src/EnergyPlus/HeatBalanceManager.cc
> +            }
Split the check for front and back thermal emissivity.

2019-08-20 13:51 UTC, Nigusse commented on src/EnergyPlus/HeatBalanceIntRadExchange.cc
> +                        }
Correct.

2019-08-20 13:52 UTC, Nigusse commented on src/EnergyPlus/HeatBalanceIntRadExchange.cc
> +                            if (SurfaceWindow(SurfNum).WindowModelType == WindowEQLModel &&
I do not see the issue after merging.

2019-08-20 13:57 UTC, Nigusse commented
Resolved merge conflict and split thermal emissivity get input check. Successfully built locally.

2019-08-22 13:34 UTC, Myoldmopar commented
I'm going to test locally where I pull in this branch as well as #7363 and compare the combination of them against develop.  I want to see the combined effects of these two changes to the equivalent layer model.

2019-08-22 15:19 UTC, Myoldmopar commented
I ran that little experiment of pulling both branches in and looking at the diffs.  As expected, the equivalent layer file is the only one with diffs.  However, those diffs are really really big now.

![image](https://user-images.githubusercontent.com/849824/63526801-9641b200-c4c5-11e9-8e2a-128018931d30.png)

I'm really uncomfortable with this much difference.  I understand the code is making it better, but it would be really great to have some more justification.  @Nigusse can you pull the two branches together and run the equivalent layer file and do some deeper analysis of the surface temperature?  It's going from 6 degrees to 16 degrees overnight.  Is it more physical of a temperature given the heat rates and other surface temperatures and boundary conditions?

I really want to get this in, but I need to be confident it's the right set of changes.

2019-08-22 16:35 UTC, Nigusse commented
@Myoldmopar Sure will look into it.

2019-08-22 20:14 UTC, Nigusse commented
OK, I pulled in both branches (Issues #7345 and #7367) locally, fixed merge conflict and investigated the defect file deeply. My finding is summarized as follows:

I looked at the WIN3 inside face temperature for winter and summer design days. Note that WIN3 has six solid layers. The plot below shows inside face temperature before and after the fix including the outside air and zone air temperatures.  Justifications for the fix:

- If you look at the winter design day (01/21) results, the before and after the fix WIN3 inside face temperatures are bounded by the outside air and zone air temperature (expected for no solar input hours). Furthermore, the after fix inside face temperature is more biased to the zone air temperature as expected for six-solid-layer window. 

- If you look at the summer design day (07/21) the before the fix WIN3 inside face temperatures are NOT BOUNDED by outside air and zone air temperature for off solar hours. This violates laws of thermodynamics hence the before the fix results are incorrect. However, for the after the fix WIN3 inside face temperatures are BOUNDED by outside air and zone air temperatures during off solar hours (this is what it should be). Also note that the after the fix WIN3 inside face temperatures during summer steadily approaches the zone air temperature during the evening hours. The after the fix WIN3 inside face temperature is behaving correctly. 

![DesignDaysWindowInsideFaceTemperature](https://user-images.githubusercontent.com/5805126/63544463-47ab0c80-c4f3-11e9-8042-be1a7ba902ca.png)

2019-08-22 20:59 UTC, Nigusse commented
@Myoldmopar Again I looked at the WIN3 inside face temperature for ZERO SOLAR summer design day. The plot below shows inside face temperature before and after the fix including the outside air and zone air temperatures. Justifications for the fix:

- the winter design day (01/21) results are the same as the previous plot, so no need repeat the explanation here. 

- If you look at the summer design day (07/21) with zero solar input. The solar was turned off deliberately to check whether the heat balance holds or not. The before the fix WIN3 inside face temperatures are NOT BOUND by outside air and zone air temperature for all day. This clearly shows the  before the fix results violates thermodynamics law. However, for the after the fix WIN3 inside face temperatures are BOUND by outside air and zone air temperatures during the entire day (as it should be). Also note that the after the fix WIN3 inside face temperatures during summer with zero solar input are very close to the zone air temperature as expected. Again the after the fix results are behaving correctly.

![ZeroSolarDesignDaysWindowInsideFaceTemperature](https://user-images.githubusercontent.com/5805126/63548911-4b439100-c4fd-11e9-988f-60c2318d53e2.png)

2019-08-22 21:02 UTC, Nigusse commented
@Myoldmopar This branch includes the fix for issue #7367 as well.

2019-08-22 21:29 UTC, rraustad commented
That's a great explanation and shows it's working correctly. It would be nice to see inside and outside face temps on that last plot (both before and after).

2019-08-23 13:32 UTC, Nigusse commented
@Myoldmopar @rraustad WIN3 outside and inside faces temperature for winter and ZERO SOLAR summer design days. The plot below shows the OUTSIDE and INSIDE face temperatures before and after the fix including the outside air, zone air and sky temperatures. Justifications for the fix:

- If you look at the summer design day (07/21) with zero solar input, the before and after the fix WIN3 outside face temperatures are similar and consistent trend because this fix does not impact the outside temperature calculation. But the very small differences observed between before and after the fix outside face temperature can be attributed to a secondary effect from the change in inside face temperature. For most part in summer design day (07/21) they are BOUND by outside air and zone air temperatures but in early morning hours during summer the outside face temperature drops below the outside and zone air temperature due to colder sky temperature as shown. In general the outside face temperature is driven by the outside air temperature when there is no solar.

- If you look at the winter design day (07/21) both outside face temperature slightly drops below the outside air temperature due to colder sky temperature (and when the outside and zone air temperatures are very close). The sky temperature is actually much colder than the outside air temperature (Atlanta Georgia Weather). This explains why the WIN3 outside face temperatures during winter (01/21) slightly drifts below the outside air temperature. Again the after the fix results are behaving correctly.

![ZeroSolarDesignDaysWindow_OutsideFace_and_InsideFaceTemperatures](https://user-images.githubusercontent.com/5805126/63595183-4aa30d00-c586-11e9-86f9-a5a66448e35d.png)

2019-08-23 15:03 UTC, Myoldmopar approved these changes

2019-08-23 15:04 UTC, Myoldmopar commented
This investigation is *so* good.  Thank you for pushing that through @Nigusse.  I feel very confident in these changes now and will merge these equivalent layer window changes in directly.

2019-08-23 15:04 UTC, merged

2019-08-23 15:36 UTC, Nigusse commented
I also compared EquivalentLayer and Winkelmann (BuiltInWindowsModel) window models for two pane clear glazing. I modified the Zn001:Wall001:Win001 of the defect file to create Winkelmann windows equivalent model. The after fix equivalent window model and the Winkelmann window model show good match for outside and inside face temperatures. The before fix inside face temperature for some hours during summer is slightly lower (this the kind of defect stated in issue #7367). The plot below shows the various temperatures for zero solar input test case.

![ZeroSolarDesignDaysWindow_OutsideFace_and_InsideFaceTemperatures_Intermadel](https://user-images.githubusercontent.com/5805126/63604194-2dc40500-c599-11e9-8be9-e115d13deed3.png)