Use correct PLR in chiller IPLV calculation
NREL/EnergyPlus pull request #7426
Opened 2019-07-30 01:16 UTC by lymereJ

Pull request overview
---------------------
In the current implementation of the chiller IPLV calculation it is assumed that the chiller PLR is equal to the different loading percentage prescribed by AHRI 550-590 (% of full load capacity). The PLR at each different loading should be recalculated as the PLR is function of the operating capacity, not the full load capacity. This is reflected in the proposed changes.

Reference issue: #7425.

2019-07-31 13:05 UTC, rraustad commented
@Nigusse could you review this change. It's either a correction to the IPLV calculation or the documentation is wrong.

2019-08-12 17:41 UTC, Nigusse commented
Reviewing the current source code indicates that percent loading is used as chiller part load ratio. Looking at the ASHRAE Std 550-590 documentation, the percent loading shall be used for calculating the load for each loading point and then use the load to calculate PLR. Thus, I agree with @lymereJ proposed fix.

2019-08-13 14:12 UTC, rraustad commented
@lymerej the engineering documentation is correct as it stands and now agrees with the code?

2019-08-13 18:33 UTC, lymereJ commented
@rraustad, yes.

2019-08-13 21:03 UTC, rraustad commented
Only thing missing here is a unit test. Not sure who will do that. In StandardRatings.unit.cc there is only 1 test for a heating coil so at minimum there needs to be a unit test for a cooling coil.

@lymereJ do you want to give that a go or should someone else do that?

2019-08-14 15:21 UTC, lymereJ commented
@rraustad, if it's not too urgent, I'd like to give it a shot.

2019-08-14 16:09 UTC, rraustad commented
Several weeks yet (mid Sep) before they lock down the next release. Easiest to copy the heating coil unit test, change the test name, and change as necessary to create a cooling coil test. If you need help along the way just ask.

2019-08-14 16:20 UTC, lymereJ commented
@rraustad, thanks, will do!

2019-08-23 21:22 UTC, rraustad commented
@lymereJ are you making any progress on a unit test?

2019-08-23 21:30 UTC, lymereJ commented
Yes, I should have something early next week.

On Aug 23, 2019, 2:22 PM, at 2:22 PM, Richard Raustad <notifications@github.com> wrote:
>@lymereJ are you making any progress on a unit test?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NREL/EnergyPlus/pull/7426#issuecomment-524466644

2019-08-26 23:27 UTC, lymereJ commented
@rraustad, I've added a unit test for the IPLV calcs. I tested it locally, it passes. Please let me know if something needs to be revised. Thanks.

2019-08-27 00:49 UTC, rraustad commented on src/EnergyPlus/ChillerElectricEIR.cc
> +                                IPLV);
@Myoldmopar do you have any reservations about adding a function argument to enable unit testing? I don't see anything wrong with this.

2019-08-27 00:49 UTC, rraustad approved these changes
Reviewed code and unit test.

2019-08-27 00:50 UTC, rraustad commented
I'm good with these changes. Can merge at will.

2019-08-27 18:36 UTC, Myoldmopar requested changes
There is a problem.  You changed the CalcChillerIPLV function signature, adding a new argument in between other arguments.  You then changed the call from ChillerElectricEIR, which is great.  But you didn't change the call from ChillerReformulatedEIR.  This is causing hard crashes in 20 input files.  You need to either fix up that function call, or, what I would prefer, would be for you to just make IPLV be a return value from this function and get rid of the new reference argument.

2019-08-27 18:36 UTC, Myoldmopar commented on src/EnergyPlus/ChillerElectricEIR.cc
> +                                IPLV);
In general, adding functionality purely for the sake of a unit test is frowned upon.  However, in this case, it doesn't have to be purely for a unit test.  Having a function called CalcIPLV return a IPLV value is justified.

2019-08-27 18:36 UTC, Myoldmopar commented on src/EnergyPlus/StandardRatings.cc
> +                         Real64 &IPLV,
Although the function could simply have returned the IPLV value rather than requiring another argument...

2019-08-27 18:36 UTC, Myoldmopar commented on src/EnergyPlus/StandardRatings.cc
> +                    PartLoadRatio = ReducedPLR(RedCapNum) / ChillerCapFT;
So this just corrects the PartLoadRatio calculation before comparing it to the minimum unload PLR.  Sounds good.

2019-08-27 18:36 UTC, Myoldmopar commented on src/EnergyPlus/StandardRatings.cc
> +        return;
I don't think this is needed.  We're already returning here.  Unless I'm misreading something on the GitHub diff view.

2019-08-27 18:36 UTC, Myoldmopar commented on tst/EnergyPlus/unit/StandardRatings.unit.cc
> +}
This appears to be a good unit test, though I'll have to rebuild it with develop merged in to see if the performance curve work affected it.

2019-08-27 18:37 UTC, Myoldmopar commented
Definitely don't merge - it's causing hard crashes in 20 test files.

2019-08-27 19:02 UTC, Myoldmopar commented
Pulled develop in, ran unit test fine.  I then fixed the code issues I mentioned above and a failing file is now working.  I think this will actually be ready to go in if CI comes in clean now.

2019-08-27 19:03 UTC, Myoldmopar approved these changes

2019-08-27 19:04 UTC, Myoldmopar commented
As an aside, @lymereJ, please use a different branch when making any submissions.  Thanks for this submission.

2019-08-28 13:47 UTC, merged

2019-08-28 13:47 UTC, rraustad commented
CI is clean now thanks to @Myoldmopar update.