Fix for Kiva initialization indoor temperature assumptions
NREL/EnergyPlus pull request #7434
Opened 2019-07-30 17:52 UTC by matthew-larson

Pull request overview
----------------
Fix for Issue #7291 - Kiva initialization indoor temperature assumptions.

Add new user input to the Foundation:Kiva object to specify the indoor air temperature for Kiva initialization during the warmup period.  If the input is left blank, the indoor air temperature during initialization will be estimated based on zone setpoints, as done previously.

### Work Checklist
- Defect: This pull request repairs a github defect issue.

## Review Checklist
- [ ] Functional code review (it has to work!)
- [ ] If defect, results of running current develop vs this branch should exhibit fix
- [ ] CI status: all green or justified
- [ ] Performance: CI Linux results include performance check
- [ ] Unit Test(s)
- C++ checks:
  - [ ] Argument types
- IDD changes:
  - [ ] Verify naming conventions and styles, memos and notes and defaults
  - [ ] Open windows IDF editor with modified IDD to check for errors
  - [ ] If transition, add to input riles files for interfaces
  - [ ] If transition, add transition source
  - [ ] If transition, update idfs
- [ ] If new idf included, locally check the err file and other outputs
- [ ] Required documentation updates

2019-07-30 18:07 UTC, nealkruis approved these changes
@mjwitte I worked with @matthew-larson on this. It looks good to me, but it would be good to have someone's eyes on it from outside of Big Ladder.

2019-08-03 02:31 UTC, Myoldmopar reviewed
If this is planned for the 9.2 release, I'd suggest getting some good CI results soon.  The branch looks to be behind develop quite a ways, so just pulling in develop and addressing my initial thoughts below would be a great start.

2019-08-03 02:31 UTC, Myoldmopar commented on src/EnergyPlus/HeatBalanceKivaManager.cc
> +        if (zoneAssumedTemperature > -999) { // default sets this below -999 at -9999 so uses value if entered
Can you just use something like `if (zoneAssumedTemperature > Kiva::DefaultWhateverTemp)` rather than a magic number?

2019-08-03 02:31 UTC, Myoldmopar commented on src/Transition/CreateNewIDFUsingRulesV9_2_0.f90
> +                 NoDiff = .false.
This needs to be described in the src/Transition/InputRules/Rules9-1-0-to-9-2-0.md file as well.

2019-08-07 18:01 UTC, mjwitte requested changes
1. I wasn't expecting to see any diffs for existing files. If these are expected, please explain why.
2. Tested transition - ok
3. Tested defect file - change in sizing results seem appropriate
4. Tested new idf file - as-is and annual - ok.
5. This needs a unit test.

2019-08-07 18:01 UTC, mjwitte commented on src/Transition/InputRulesFiles/Rules9-1-0-to-9-2-0.md
> +Shift all later numeric fields down by 1. The old input fields N1 - N39 become the new N2-N40.
Fine point - but this should say "Shift all later ~numeric~ fields down by 1 . . . F2:F??? become the new F3:F???." The transition code is correct.

2019-08-09 21:23 UTC, matthew-larson commented on src/Transition/InputRulesFiles/Rules9-1-0-to-9-2-0.md
> +Shift all later numeric fields down by 1. The old input fields N1 - N39 become the new N2-N40.
I've updated the transition rule description and resolved the diffs for the existing files.

2019-08-12 13:38 UTC, Myoldmopar approved these changes

2019-08-12 13:47 UTC, mjwitte commented
Diffs are gone. Just waiting on a new unit test or extending an existing one. Then this can drop in.

2019-08-15 21:16 UTC, matthew-larson commented
I just pushed up a unit test for this issue.

2019-08-16 00:28 UTC, mjwitte approved these changes

2019-08-16 00:31 UTC, merged