Add Boiler Efficiency output for Boiler objects
NREL/EnergyPlus pull request #8067
Opened 2020-06-09 22:15 UTC by matthew-larson

Pull request overview
---------------------
 - Fixes #8064 
 - This pull request adds output variables for Boiler (Steam) Efficiency for the Boiler:HotWater and Boiler:Steam objects.  This provides an efficiency output variable for the Boiler objects similar to other plant objects like the Chiller objects providing a Chiller COP output variable.  For simplification purposes, I changed the variable Effic for boiler efficiency at design conditions to NomEffic, similar to NomCap, and created a new variable BoilerEff to be the outputted variable for each timestep.  Unit tests were created to ensure the BoilerEff variable result is correct.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts

2020-06-17 22:26 UTC, mitchute requested changes
Minor doc changes requested in the IORef but this looks good other than that. Running tests locally now.

2020-06-17 22:26 UTC, mitchute commented on doc/input-output-reference/src/overview/group-plant-equipment.tex
> +
I like the note, but just for the sake of uniformity and completeness, we should probably also have an explicit definition of efficiency. Maybe add something like "this output is boiler heating rate divided by boiler gas rate" or similar between the label and the note.

2020-06-17 22:26 UTC, mitchute commented on doc/input-output-reference/src/overview/group-plant-equipment.tex
> +
Same change here.

2020-06-17 22:26 UTC, mitchute commented on src/EnergyPlus/BoilerSteam.cc
> +            thisBoiler.NomEffic = DataIPShortCuts::rNumericArgs(2);
More explicit. This is good.

2020-06-17 22:26 UTC, mitchute commented on tst/EnergyPlus/unit/BoilerHotWater.unit.cc
> +
Unit tests look good.

2020-06-18 12:25 UTC, mitchute commented
Unit tests look good, and I ran a few files and the results look good. We also need to add the new output variables to a least one file for the Boiler:HotWater and Boiler:Steam objects.

2020-06-18 19:16 UTC, matthew-larson commented
@mitchute I added descriptions for the output variables as requested and also added the output variables to a few files with Boiler:HotWater and Boiler:Steam objects that were outputting similar variables.

2020-06-18 19:33 UTC, mitchute approved these changes

2020-06-18 19:34 UTC, mitchute commented
Thanks, @matthew-larson. This should go in once CI reports back.

2020-06-19 13:09 UTC, matthew-larson commented
Just pushed up changes to fix the build errors.

2020-06-19 16:52 UTC, mitchute commented
AUD and RDD diffs are expected here. Merging.

2020-06-19 16:52 UTC, merged