ZoneHVAC:HybridUnitaryHVAC ERR object type output
NREL/EnergyPlus pull request #8326
Opened 2020-09-30 16:04 UTC by matthew-larson

Pull request overview
---------------------
 - Fixes #8316 
 - This pull request corrects an inconsistent variable name for the Object type related to the ZoneHVAC:HybridUnitaryHVAC object.  This was being referenced as "cCurrentModuleObject" in some places when "CurrentModuleObject" was the original string variable name.  I changed all of the references to "cCurrentModuleObject" to match the majority of other Object type variable names for objects.  I added a unit test to check the error that presented this issue but since all the other unit tests for this module are disabled due to another potential issue, I disabled this test as well, but does work correctly on my machine.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

2020-10-16 21:39 UTC, mjwitte commented
@Myoldmopar You disabled some HybridUnitary unit tests in https://github.com/NREL/EnergyPlus/commit/799b65031d8d896e65ff411a01062ee8a70316a4. They run fine locally. Any reason to keep them disabled?

2020-10-16 21:40 UTC, Myoldmopar commented
If they are running fine go ahead and re-enable them.

2020-10-16 21:56 UTC, mjwitte requested changes
@matthew-larson Please merge in develop and resolve conflicts and address these other comments.

2020-10-16 21:56 UTC, mjwitte commented on src/EnergyPlus/HybridUnitaryAirConditioners.cc
>                      ShowContinueError("Invalid-not found" + cAlphaFieldNames(19) + "=\"" + Alphas(19) + "\".");
The object type for the error message is fixed now, but the error message is still basically empty:
```
   ** Severe  ** GetInputZoneHybridUnitaryAirConditioners: ZoneHVAC:HybridUnitaryHVAC = MUNTERSEPX5000 invalid data
   **   ~~~   ** Invalid-not found="".
```
In the call to `getObjectItem`, the field names are returned in `cAlphaFields`. Some error messages use this variable, but a few (like the error shown here) are using `cAlphaFieldNames` which is blank. Replace all of these with `cAlphaFields` and the error message should show the field name that's in error.

2020-10-16 21:56 UTC, mjwitte commented on tst/EnergyPlus/unit/UnitaryHybridAirConditioner.unit.cc
> +TEST_F(EnergyPlusFixture, DISABLED_Test_UnitaryHybridAirConditioner_ValidateError)
Please enable this unit test and all of the other hybrid unitary tests. They run fine locally here.

2020-10-19 14:21 UTC, nealkruis commented
@mjwitte It may be fine to enable the hybrid unitary tests, but I remember seeing this from @Myoldmopar:

> so when I try to run the full unit test suite in debug it is failing on the hybrid unitary tests:
> ```
> 0x000055555629cca5 in EnergyPlus::Psychrometrics::PsyRhFnTdbWPb (TDB=0, dW=0, PB=0, CalledFrom="InitZoneHybridUnitaryAirConditioners")
>     at /eplus/repos/myoldmopar/src/EnergyPlus/Psychrometrics.hh:920
> 920	        Real64 const RHValue(U / (1.0 - (1.0 - U) * (PWS / PB)));
> ```
> If you run them individually, they pass, but something is not being cleaned up
> https://github.com/NREL/EnergyPlus/blob/9fc1e480c4ad709944629b0f3259a4e643621c91/src/EnergyPlus/HybridUnitaryAirConditioners.cc#L205

@matthew-larson looked into this a bit and couldn't reproduce the issue. Do we still want to move forward with enabling them?

2020-10-19 14:43 UTC, mjwitte commented
@nealkruis I ran all of the hybrid unit tests serially and it was fine here (Windows 10). I'm running everything now. Moving that to the namespace likely corrected the problem. Either way, these need to be enabled. If there's still a problem, then it can be fixed.

2020-10-19 16:11 UTC, matthew-larson commented
@mjwitte I updated the code based on your comments and also re-enabled the unit tests.  Tests all run successfully for me locally.

2020-10-19 21:09 UTC, mjwitte commented
@matthew-larson That's better.
```
   ** Severe  ** GetInputZoneHybridUnitaryAirConditioners: ZoneHVAC:HybridUnitaryHVAC = MUNTERSEPX5000 invalid data
   **   ~~~   ** Invalid-not found Design Specification Outdoor Air Object Name="".
```
But why is this an error? The IDD implies that this field is optional.

@Myoldmopar Any idea what happened with the [windows CI failure](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-b8404b1294c3ce246adc79aeb4977e4baaa5a722-PR8326-Win64-Windows-10-VisualStudio-16.html)?

2020-10-20 15:21 UTC, matthew-larson commented
@mjwitte that's a great point about that particular field being optional.  Digging into it a little, the `ZoneHybridUnitaryAirConditioner(UnitLoop).OutdoorAir` method isn't actually being used for anything and if `ZoneHybridUnitaryAirConditioner(UnitLoop).OARequirementsPtr` is zero, it just sets the minimum ventilation rate to 0 further in the code, which is the intent.  Based on this, I'm tempted to just remove the if/else statement altogether here.  I can modify the unit test to present a different error the shows the correct module object.

```
        // A19, \ OA requirement pointer
        ZoneHybridUnitaryAirConditioner(UnitLoop).OARequirementsPtr = UtilityRoutines::FindItemInList(Alphas(19), OARequirements);
        if (ZoneHybridUnitaryAirConditioner(UnitLoop).OARequirementsPtr == 0) {
            ShowSevereError(RoutineName + cCurrentModuleObject + " = " + Alphas(1) + " invalid data");
            ShowContinueError("Invalid-not found " + cAlphaFields(19) + "=\"" + Alphas(19) + "\".");
            ErrorsFound = true;
        } else {
            ZoneHybridUnitaryAirConditioner(UnitLoop).OutdoorAir = true;
        }
```

2020-10-20 15:25 UTC, mjwitte commented
@matthew-larson This still needs to trap an invalid non-blank OA specification object name. For optional fields without a default, the input processing should check if the field is blank (using the logical array that's returned from `getObjectItem`) then skip it, but if it's not blank, then get the pointer and throw an error if it's still zero.

2020-10-20 16:38 UTC, matthew-larson commented
@mjwitte that makes sense.  I modified the code as shown below, which I believe now acts as intended to check if the field is blank, otherwise grab the pointer and throw an error if 0.

```
                // A19, \ OA requirement pointer
                if (!lAlphaBlanks(19)) {
                    ZoneHybridUnitaryAirConditioner(UnitLoop).OARequirementsPtr = UtilityRoutines::FindItemInList(Alphas(19), OARequirements);
                    if (ZoneHybridUnitaryAirConditioner(UnitLoop).OARequirementsPtr == 0) {
                        ShowSevereError(RoutineName + cCurrentModuleObject + " = " + Alphas(1) + " invalid data");
                        ShowContinueError("Invalid-not found " + cAlphaFields(19) + "=\"" + Alphas(19) + "\".");
                        ErrorsFound = true;
                    } else {
                        ZoneHybridUnitaryAirConditioner(UnitLoop).OutdoorAir = true;
                    }
                }
```

2020-10-20 16:46 UTC, mjwitte commented
@matthew-larson Yes, like that. While you're in there, it would be good to review all of the other optional fields in the (massive) object to see if they are all being processed correctly. I suppose a test file with all optional fields left blank should expose any problems.

2020-10-27 14:40 UTC, matthew-larson commented on doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
> +This alpha input field specifies the name of the HVAC system node from which the hybrid unit draws outdoor air. This node name must also be specified in an \hyperref[outdoorairnode]{OutdoorAir:Node}
The IDD has this as a required field so I just removed the statement about leaving the field blank.

2020-10-27 17:48 UTC, matthew-larson commented
@mjwitte I cleaned up a couple more optional fields to prevent incorrect errors and updated the unit test with optional fields left blank.

2020-10-28 13:21 UTC, mjwitte reviewed
@matthew-larson Almost there.

2020-10-28 13:21 UTC, mjwitte commented on doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
> +This alpha input field specifies the name of the HVAC system node from which the hybrid unit draws outdoor air. This node name must also be specified in an \hyperref[outdoorairnode]{OutdoorAir:Node}
Good catch. But the code for this input is wrong. See comment below.

2020-10-28 13:21 UTC, mjwitte commented on src/EnergyPlus/HybridUnitaryAirConditioners.cc
>                                                                                                   NodeConnectionType_OutsideAirReference,
This is kind of nit-picky, but `NodeConnectionType_OutsideAirReference` should be `NodeConnectionType_OutsideAir` because this node is a real outdoor air node with flow, not just a sensor.

2020-10-28 13:21 UTC, mjwitte commented on src/EnergyPlus/HybridUnitaryAirConditioners.cc
> +                        ShowContinueError("Entered in " + cCurrentModuleObject + '=' + cAlphaArgs(1));
Made a test file with bad inputs in a bunch of fields, and some of the error messages are still broken:
```
   ** Severe  ** Invalid Minimum Supply Air Temperature Schedule Name=XMINSUPPLYT
   **   ~~~   ** Entered in ZoneHVAC:HybridUnitaryHVAC=MAIN ZONE BASEBOARD
```
`cAlphaArgs` should be `Alphas` here and elsewhere. Here's the test file:
[UnitaryHybridAC_bug-ForceErrors1.idf.txt](https://github.com/NREL/EnergyPlus/files/5451931/UnitaryHybridAC_bug-ForceErrors1.idf.txt)

2020-11-03 22:14 UTC, mjwitte commented
@matthew-larson Almost there, no more `cAlphaArgs` lurking. But there are still 2 instances of `cAlphaFieldNames` that need to be fixed.

2020-11-04 17:09 UTC, mjwitte approved these changes
All good now. Merging.

2020-11-04 17:09 UTC, merged