[NewFeature] Implementation and integration of ice rink module
NREL/EnergyPlus pull request #8436
Opened 2020-12-25 00:33 UTC by miroavs

Pull request overview
---------------------
 - This module is a new feature in EnergyPlus. It allows the user to simulate an ice rink. This pull request is to provide a progress update on the module development and obtain feedback. The module is not complete and still being worked on. 
 #### Future tasks includes:
 - Connect the ice rink to a chiller. Currently, a simple plant is used in the IDF.
 - Still working on the update and  UpdateIceRinkSourceValAvg functions.
 - Add resurfacer load

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

2021-02-05 17:05 UTC, mjwitte commented
@miroavs I'm assuming this won't be complete for the v9.5 I/O Freeze on Feb 15. So I'm setting the milestone to Future.

2021-02-10 14:09 UTC, Myoldmopar commented
@miroavs I'm doing a review of the code now, but as you can see, this is still failing on our machines, so it is definitely not ready to go yet.  It looks like the failure is just in the unit test file, should be an easy fix for you.

2021-02-10 15:12 UTC, Myoldmopar requested changes
Definitely still some changes needed, but this is coming along nicely.  Let me know if you have any questions.  The CI build is still failing so I can't see the unit test coverage but I would expect the unit tests here to ultimately cover a major portion of the new code.

2021-02-10 15:12 UTC, Myoldmopar commented on idd/Energy+.idd.in
> +       \default STC
I think it would be better to use the full wording here in `PascalCaseText` rather than the acronyms.  @mjwitte ?

2021-02-10 15:12 UTC, Myoldmopar commented on idd/Energy+.idd.in
> +       \type node
These need to be required fields, right?

2021-02-10 15:12 UTC, Myoldmopar commented on idd/Energy+.idd.in
> +       \memo Indoor ice rink with a direct refrigeration system integrated with a floor.
I would put a `min-fields` tag on the object here to specify the minimum required fields.  For this object, I believe it would be 16? (Since the 16th field is the last required one)

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +    Array1D<Real64> LastTimeStepSys;    // Need to keep the last value in case we are still iterating
I don't really get why these global variables aren't in the dataIceRink data class for this namespace.  I think they should be, and you can ping me to discuss how to move them over.

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +        FirstTimeInit = true;
There are global variables above that are not reset in this clear_state method.   This particular clear_state method won't be needed once you move over to the data class, but still you'll need to make sure you reset _all_ the data.

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +            // GetResurfacer();
So GetResurfacer isn't needed here anymore?

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +            this->calculateIceRink(state, CurLoad); //"false" is for unit testing
I don't see an argument here that could be `false`.  I wonder if this is something that was removed along the way and the comment is just invalid now. :shrug:

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +            } else if (UtilityRoutines::SameString(cAlphaArgs(5), "STC")) {
These two spots would need to be updated if the IDD was changed from acronyms to keywords.

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +        Real64 CpIce(2108.00);
In general if you have absolute constants that are known at compile time, I think we should mark them as `constexpr` just to be clear.

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +        FreezingLoad = QFreezing;
Just return `QFreezing` here and eliminate the `FreezingLoad` variable entirely.  The compiler is surely already doing this, but strive to make your code as simple as possible.

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +        if (this->operation == 1) { // If schedule's value equals to 1 then Ice Rink is ON.
What if the user schedules to something greater than 1?  And also maybe it's worth accounting for some variation in the floating point value.  I think a better pattern might be `if (this->operation > 0)`.

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +                    QRadSysSource(SurfNum) = (this->Q); // This the Q to updtate the EnergyPlus heat balance to get new surface temperatures
These two IF blocks look identical, am I missing something?

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +        // if (PlantLoop(LoopNum).LoopSide(LoopSideNum).FlowLock > 0) {
Remove these comments.

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.cc
> +        // QRadSysSource = QRadSysSrcAvg;
Remove comments here.

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.hh
> +    extern int const EG;
Try hard to change `int const` lists to `enum class` groups.  Let me know if you need assistance.

2021-02-10 15:12 UTC, Myoldmopar commented on src/EnergyPlus/IndoorIceRink.hh
> +    extern Array1D<IceRinkData> Rink;
All the non-const extern data needs to be moved into the `IceRinkData` class below and initialized in the `clear_state` method.

2021-02-10 15:12 UTC, Myoldmopar commented on tst/EnergyPlus/unit/IndoorIceRink.unit.cc
> +//}
Any reason these had to be commented out?  If they aren't relevant then just delete them.

2021-02-10 17:12 UTC, mjwitte commented on idd/Energy+.idd.in
> +       \default STC
I agree, BrineOutletTemperatureControl and IceSurfaceTemperatureControl if I'm following correctly.
Or change the field to be "Ice Rink Control Temperature" with choices of "BrineOutlet" and "IceSurface" ?

2021-02-10 17:12 UTC, mjwitte commented on idd/Energy+.idd.in
> +       \type node
Are the flow rates autosizable? Could they be?

2021-02-10 17:12 UTC, mjwitte commented on idd/Energy+.idd.in
> +       \type node
I question the name "Refrigerant" here. I'm not sure what the standard terminology is in the ice rink world, but to me "Refrigerant" implies a phase-change fluid like R134a.
If I'm following correctly (based on the example idf) this is using an EnergyPlus plant loop with a glycol mixture - so it's not a refrigerant and it's not a brine even, it should be called Chilled Water?
I don't see the NFP attached here - that needs to be added for context.

2021-02-10 17:12 UTC, mjwitte commented on idd/Energy+.idd.in
> +  A8 , \field Refrigerant Outlet Temperature Schedule Name
All schedules that have units need a \note to say what the units the schedule values should be. The two temperature schedules and the heat gain schedule.

2021-02-10 17:12 UTC, mjwitte commented on idd/Energy+.idd.in
> +  N8 , \field Water Temperature
"Initial Rink Water Temperature" to be more specific?

2021-02-10 17:12 UTC, mjwitte commented on idd/Energy+.idd.in
> + N10 , \field Flood Water Temperature
This is different from the water temperature above?

2021-06-22 03:05 UTC, Myoldmopar commented
Any update on here?  There are lots of conflicts and I would be happy to help resolve them but I don't want to start making changes if there are other code changes that haven't been pushed.  Which seems likely since it hasn't had a commit in quite a while.

2022-04-12 23:53 UTC, Myoldmopar commented
Forked repo deleted, and this is conflicted.  Perhaps we can pick this up sometime, but not now.

2022-04-12 23:53 UTC, closed without merging

2023-04-18 02:30 UTC, gf230 commented on idd/Energy+.idd.in
> +       \memo Indoor ice rink with a direct refrigeration system integrated with a floor.
Hi ! I want to consult that how to use this ice rink energy+ file. I always simulate by idf. file in energyplsu or in grasshopper/honeybee platform. but for this, totally have no clue

2024-03-11 04:14 UTC, paul-caicedo commented
Hi @Myoldmopar 
Do you think that this feature will be open again for E+ V24?

2024-03-15 21:02 UTC, Myoldmopar commented
Perhaps 24.2, but not 24.1.  If you have interest in contributing effort to help get it in, I'm happy to help, but I don't think our team has any time available to work on it otherwise.